{
  "formatVersion": "1.1",
  "component": {
    "group": "androidx.credentials",
    "module": "credentials-play-services-auth",
    "version": "1.2.0-rc01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.3"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.2.0-rc01"
          },
          "reason": "credentials-play-services-auth is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-play-services-auth-1.2.0-rc01.aar",
          "url": "credentials-play-services-auth-1.2.0-rc01.aar",
          "size": 129144,
          "sha512": "0db28b2fd8fbcb55f595873cfdbd5792d818d0f24223671503a6566fb2f205110db23f9b50b4c7ed47ec4588264b5f29193daa50cbd1eb836c4fc9001dde3069",
          "sha256": "5830a641384e9796415b30f34dc250782d7808101cf692363460d93939a020c9",
          "sha1": "deb70dd8ebfdbb31ea881c1c3f195dabf2d720fb",
          "md5": "46b1ac89e0a80eaff73b661d3fac0c07"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.2.0-rc01"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "20.7.0"
          },
          "excludes": [
            {
              "group": "androidx.loader",
              "module": "*"
            },
            {
              "group": "androidx.core",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-fido",
          "version": {
            "requires": "20.1.0"
          },
          "excludes": [
            {
              "group": "androidx.loader",
              "module": "*"
            },
            {
              "group": "androidx.core",
              "module": "*"
            }
          ]
        },
        {
          "group": "com.google.android.libraries.identity.googleid",
          "module": "googleid",
          "version": {
            "requires": "1.1.0"
          },
          "excludes": [
            {
              "group": "androidx.credentials",
              "module": "*"
            }
          ]
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.2.0-rc01"
          },
          "reason": "credentials-play-services-auth is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-play-services-auth-1.2.0-rc01.aar",
          "url": "credentials-play-services-auth-1.2.0-rc01.aar",
          "size": 129144,
          "sha512": "0db28b2fd8fbcb55f595873cfdbd5792d818d0f24223671503a6566fb2f205110db23f9b50b4c7ed47ec4588264b5f29193daa50cbd1eb836c4fc9001dde3069",
          "sha256": "5830a641384e9796415b30f34dc250782d7808101cf692363460d93939a020c9",
          "sha1": "deb70dd8ebfdbb31ea881c1c3f195dabf2d720fb",
          "md5": "46b1ac89e0a80eaff73b661d3fac0c07"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.2.0-rc01"
          },
          "reason": "credentials-play-services-auth is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-play-services-auth-1.2.0-rc01-sources.jar",
          "url": "credentials-play-services-auth-1.2.0-rc01-sources.jar",
          "size": 30511,
          "sha512": "9241445818e5b097ed3dd9740f448c5c1a2787dfc4a17724167fe20722bab2179f93003c2dea7a981c9c7213462b9b727ea9ee229c1d6809ba0e5ac1b2a568f1",
          "sha256": "eeccdb5403cef6fff7bc387f5fd9e1449a522b7e0378aee1692a2aca040784f8",
          "sha1": "b37387d4ad4bec8918c961d584bf738274e48d38",
          "md5": "1e075c82049d17e9a3973beab164b7b1"
        }
      ]
    },
    {
      "name": "libraryVersionMetadata",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.usage": "library-version-metadata"
      },
      "dependencyConstraints": [
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.2.0-rc01"
          },
          "reason": "credentials-play-services-auth is in atomic group androidx.credentials"
        }
      ],
      "files": [
        {
          "name": "credentials-play-services-auth-1.2.0-rc01-versionMetadata.json",
          "url": "credentials-play-services-auth-1.2.0-rc01-versionMetadata.json",
          "size": 2,
          "sha512": "b25b294cb4deb69ea00a4c3cf3113904801b6015e5956bd019a8570b1fe1d6040e944ef3cdee16d0a46503ca6e659a25f21cf9ceddc13f352a3c98138c15d6af",
          "sha256": "4f53cda18c2baa0c0354bb5f9a3ecbe5ed12ab4d8e11ba873c2f11161202b945",
          "sha1": "97d170e1550eee4afc0af065b78cda302a97674c",
          "md5": "d751713988987e9331980363e24189ce"
        }
      ]
    }
  ]
}